# Generated by Django 5.1.2 on 2024-12-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_quizzes_attempted_topicperformance_questions_attempted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslist',
            name='access_end_time',
        ),
        migrations.RemoveField(
            model_name='accesslist',
            name='access_start_time',
        ),
        migrations.AddField(
            model_name='quiz',
            name='access_end_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='access_start_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
