# Generated by Django 5.1.2 on 2024-12-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_accesslist_access_end_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accesslist',
            unique_together={('email', 'quiz')},
        ),
    ]
