# Generated by Django 5.1.2 on 2025-01-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_accesslist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='topic',
            field=models.CharField(default='others', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='topicsAndScores',
            field=models.JSONField(default=dict),
        ),
    ]
