# Generated by Django 5.1.2 on 2025-01-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_response_topic_user_total_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
