# Generated by Django 5.1.2 on 2025-01-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('coding', 'Coding')], default='multiple_choice', max_length=50),
        ),
    ]
