# Generated by Django 5.1.2 on 2025-01-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_quiz_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.CharField(default='coding', max_length=100),
        ),
    ]
